---
title: "nexus"
author: "Ethan de Villiers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r Init commands}
#> Download and install necessary packages
library(devtools) 
source_url("https://raw.githubusercontent.com/hdg204/UKBB/main/UKBB_Health_Records_New_Project.R") 

install.packages('tidyverse')
library(tidyverse)

#> Download my codelist file: runs through terminal
system('dx download file-GbJv5YjJj59f02q8P6qybYgX')

#> Load in codelist data as compiled_codelist.csv
df = read_csv('compiled_codelist.csv')
```

``` {r Loading VIRAL Infection Data}
#> Reading Viral data into temp df
temp = read_ICD10(
  df %>%
  filter(Infection == "viral") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had viral infection 3779 eids, 2006 unique
viral_eids = temp %>%
  select(eid) %>% 
  pull()

#> Copy baseline_table, mutating infection_type column to "viral" if any patient IDs are found in viral_eids
infections_df = baseline_table %>%
  mutate(infection_type = ifelse(eid %in% unique(viral_eids), "viral", NA))

#> Check if baseline table contains same number viral infected as length(unique(viral_eids)) = 2006
infections_df %>%
  filter(infection_type == "viral") %>%
  count()
```

``` {r Loading FUNGAL Infection Data}
#> Reading FUNGAL data into temp df
temp = read_ICD10(
  df %>%
  filter(Infection == "fungal") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had fungal infection: 3883 eids, 1829 unique
#> A LOT MORE RECURRING INFECTIONS! 
fungal_eids = temp %>%
  select(eid) %>% 
  pull()

#> edit copy of baseline_table (infections_df), mutating infection_type column to "fungal" if any patient IDs are found in fungal_eids
infections_df = infections_df %>%
  mutate(infection_type = ifelse(eid %in% unique(fungal_eids), "fungal", infection_type))

#> Check if baseline table contains same number fungal infected as length(unique(fungal_eids)) = 1829
infections_df %>%
  filter(infection_type == "fungal") %>%
  count()

#> Make sure that fungal + viral infections (= !is.na(infection_type)) < 1829 + 2006 = 3835
#> Received value of 3787, showing some patients reinfected!
infections_df %>%
  filter(!is.na(infection_type)) %>%
  count()
```

``` {r Loading BACTERIAL Infection Data}
#> Reading BACTERIAL data into temp df
temp = read_ICD10(
  df %>%
  filter(Infection == "bacterial") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had bacterial infection: 139,481 eids, 51,594 unique
bacterial_eids = temp %>%
  select(eid) %>% 
  pull()

#> edit copy of baseline_table (infections_df), mutating infection_type column to "bacterial" if any patient IDs are found in bacterial_eids
infections_df = infections_df %>%
  mutate(infection_type = ifelse(eid %in% unique(bacterial_eids), "bacterial", infection_type))

#> Check if baseline table contains same number bacterial infected as length(unique(bacterial_eids)) = 51,594
infections_df %>%
  filter(infection_type == "bacterial") %>%
  count()

#> Make sure that fungal + viral + bacterial infections (= !is.na(infection_type)) < 1829 + 2006 + 51,594 = 55,429
#> Received value of 53,462, showing some patients reinfected!
infections_df %>%
  filter(!is.na(infection_type)) %>%
  count()
```

``` {r Saving Cohort}
#> Export 212 MiB dataframe of infections to Harry's New Project
#> At £0.0141/GB Per month = 0.223 * 0.0141 / 30 = £0.0001 per day

write_csv(
  infections_df,
  file = "infections_df_20112023.csv"
)

system('dx upload infections_df_20112023.csv')
```

``` {r GGplot Histogram of HbA1c}
#> generates large pretty useless graph due to NA being so rampant
ggplot(
  infections_df %>%
    mutate(infection_type = ifelse(is.na(infection_type), "none", infection_type)),
  aes(x=hba1c, group=infection_type, fill=infection_type)
) + 
  geom_histogram(alpha=0.25, position="identity") +
  scale_x_continuous(limits = c(0, 140)) +
  scale_colour_brewer(palette = "Dark2")

#> generates 4-part, log-scaled plot showcasing HbA1c distributions by infections type
ggplot(
  infections_df %>%
    mutate(infection_type = ifelse(is.na(infection_type), "none", infection_type)),
  aes(x=hba1c, fill=infection_type)
) + 
  geom_histogram() +
  scale_x_continuous(limits = c(0, 140)) +
  scale_colour_brewer(palette = "Dark2") +
  facet_wrap(~ infection_type, scales = 'free') +
  labs(
    title = 'HbA1c by infection'
  )

```

``` {r GG_Hist of Age and other features}
#> BMI 4 part infections plot
ggplot(
  infections_df %>%
    mutate(infection_type = ifelse(is.na(infection_type), "none", infection_type)),
  aes(x=bmi, fill=infection_type)
) + 
  geom_histogram() +
  scale_x_continuous(limits = c(10, 60)) +
  scale_colour_brewer(palette = "Dark2") +
  facet_wrap(~ infection_type, scales = "free") +
  labs(
      title = "BMI distributions by infections"
  )

#> AGE 4 part infections plot
ggplot(
  infections_df %>%
    mutate(infection_type = ifelse(is.na(infection_type), "none", infection_type)),
  aes(x=assess_age, fill=infection_type)
) + 
  geom_histogram() +
  scale_x_continuous(limits = c(35, 80)) +
  scale_colour_brewer(palette = "Dark2") +
  facet_wrap(~ infection_type, scales = "free") +
  labs(
      title = "Age distributions by infections"
  )

#> HBA1c infected vs non-infected
ggplot(
  infections_df %>%
    mutate(infection_type = ifelse(is.na(infection_type), "none", "infected")),
  aes(x=hba1c, fill=infection_type)
) + 
  geom_histogram(alpha=0.3, position="identity") +
  scale_x_continuous(limits = c(0,140)) +
  facet_wrap(~ infection_type, scales = "free") +
  labs(
      title = "HbA1c of Infections vs Non-infections (NoLim)"
  )

# ggplot(
#   infections_df %>%
#     mutate(
#       infection_type = ifelse(is.na(infection_type), "none", "infected"),
#     ),
#   aes(x=hba1c, fill=infection_type)
# ) + 
#   ylim(c(0,5000)) +
#   geom_histogram(alpha=0.3, position="identity") +
#   scale_x_continuous(limits = c(0,140)) +
#   facet_wrap(~ infection_type, scales = "free") +
#   labs(
#       title = "HbA1c of Infections vs Non-infections (Lims)"
#   )

```

``` {r Quick T-Test}
t.test(
  infections_df %>%
    filter(!is.na(infection_type))%>%
    select(hba1c) %>%
    pull(),
  infections_df %>%
    filter(is.na(infection_type))%>%
    select(hba1c) %>%
    pull()
)

```