---
title: "Intro"
author: "Ethan de Villiers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

``` {r Creating Dataframe of Codelist}
#> Save list of codelists in "~/Codes/" directory as list_codelists
list_codelists = list.files(path="./Codes")

#> Create list of fungal codelists
fungal_codelist = c("exeter_icd10_genitalinfection_fungal.txt", "exeter_icd10_skininfection_fungal.txt")

#> Create list of bacterial codelists
bacterial_codelist = c("exeter_icd10_pneumonia_bacterial.txt", "exeter_icd10_skininfection_bacterial.txt")

#> Create list of Viral codelists
viral_codelist = c("exeter_icd10_influenza.txt")

#> Create empty dataframe
df = data.frame() 

#> Read all fungal data into df
for (fungal in fungal_codelist){
  print(paste0("./Codes/", fungal))
  df = rbind(
    df,
    read.table(
      paste0("./Codes/", fungal), 
      sep="\t",
      skip = 1
    ) %>%
      mutate(Infection = "fungal")
  )
}

#> Read all viral data into df
for (viral in viral_codelist){
  print(paste0("./Codes/", viral))
  df = rbind(
    df,
    read.table(
      paste0("./Codes/", viral), 
      sep="\t",
      skip = 1
    ) %>%
      mutate(Infection = "viral")
  )
}

#> Read all viral data into df
for (bacterial in bacterial_codelist){
  print(paste0("./Codes/", bacterial))
  df = rbind(
    df,
    read.table(
      paste0("./Codes/", bacterial), 
      sep="\t",
      skip = 1
    ) %>%
      mutate(Infection = "bacterial")
  )
}

#> CLeaning Up DF
df = df %>%
  rename(
    ICD10 = V1,
    Description = V2
  )

#> Clean Environment
remove(bacterial, fungal, viral)
```

``` {r Export codelist df for DNANexus use}
#> Writing file to csv for DNA Nexus use
write.csv(df, "compiled_codelist.csv", row.names=FALSE)

```

``` {r Pull Codes:}
#> Pull Any Codes:

df %>%
  filter(Infection == "bacterial") %>%
  select(ICD10) %>%
  pull()

```


```{r }




```
