---
title: "nexus"
author: "Ethan de Villiers"
date: "`r Sys.Date()`"
output: html_document
---

``` {r Packages & Init}
#> ----------------------------- Packages & Init ---------------------------- <#
install.packages('tidyverse')
library(tidyverse)

library(devtools) 
source_url("https://raw.githubusercontent.com/hdg204/UKBB/main/UKBB_Health_Records_New_Project.R") 

#> Download my codelist file: runs through terminal
system('dx download file-GbJv5YjJj59f02q8P6qybYgX')

#> Load in codelist data as compiled_codelist.csv
codelist = read_csv('compiled_codelist.csv')


#> ----------------------------- Troubleshooting ---------------------------- <#
# If giving persistent problems when downloading/updating, try this:
update.packages(ask = FALSE)
```

``` {r Loading VIRAL Infection Data}
#> Reading Viral data into temp df
temp = read_ICD10(
  codelist %>%
  filter(Infection == "viral") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had viral infection 3779 eids, 2006 unique
viral_eids = temp %>%
  select(eid) %>% 
  pull()


#> 2 step pipe:
#> Create infections_df for later use based on baseline_table
#> Create new column, viral = 1/0 if eid matches from viral_eids
infections_df = baseline_table %>%
  mutate(
    viral = as.logical( eid %in% viral_eids ),
    viral_multiple = as.logical( eid %in% viral_eids[duplicated(viral_eids)] )
  )


#> ---------------------- Bacterial -------------------------------- <#
#> Reading Bacterial data into temp df
temp = read_ICD10(
  codelist %>%
  filter(Infection == "bacterial") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had bacterial infection: 139,481 eids, 51,594 unique
bacterial_eids = temp %>%
  select(eid) %>% 
  pull()


infections_df = infections_df %>%
  mutate(
    bacterial = as.logical( eid %in% bacterial_eids ),
    bacterial_multiple = as.logical( eid %in% bacterial_eids[duplicated(bacterial_eids)] )
  )

#> ---------------------- Fungal -------------------------------- <#
#> Reading Fungal data into temp df
temp = read_ICD10(
  codelist %>%
  filter(Infection == "fungal") %>%
  select(ICD10) %>%
  pull()
)

#> Store a list of patient IDs who have had fungal infection: 3883 eids, 1829 unique
fungal_eids = temp %>%
  select(eid) %>% 
  pull()


infections_df = infections_df %>%
  mutate(
    fungal = as.logical( eid %in% fungal_eids ),
    fungal_multiple = as.logical( eid %in% fungal_eids[duplicated(fungal_eids)] )
  )

#> ------------------ CONTROL ---------------- <#
infections_df = infections_df %>%
  mutate(control = ifelse( !viral & !bacterial & !fungal, TRUE, FALSE))


#> ------------------- CATEGORIES ------------------------ <#
infections_df = infections_df %>%
  mutate(
    infection_type = case_when(
      viral & !bacterial & !fungal ~ "viral",
      !viral & bacterial & !fungal ~ "bacterial",
      !viral & !bacterial & fungal ~ "fungal",
      viral & bacterial & !fungal | viral & !bacterial & fungal | !viral & bacterial & fungal | viral & bacterial & fungal ~ "mixed",
      TRUE ~ "control"
    )
  )
```

``` {r GRS}
#> Harry already has 4 GRS csv scores generated for BIOBANK individuals
#> Just need to load .csv files and left join by eid

#> ------------------- DOWNLOADING GRS DATA ------------------------ <#
system('dx download file-Gfb6y6jJj59vZK866f7Pxzg1')
system('dx download file-Gfb6y7QJj59VxF3fPG9qbGBJ')
system('dx download file-Gfb6y80Jj59qzY761Yf0qbg6')
system('dx download file-Gfb6y8jJj59Xv5x80pFkpKZj')

th_grs_lookup = read_csv("2hGlu_grs.csv")
fg_grs_lookup = read_csv("FG_grs.csv")
glyhba1c_grs_lookup = read_csv("HbA1c_gly_grs.csv")
nonhba1c_grs_lookup = read_csv("HbA1c_non_gly_grs.csv")


#> ------------------- LEFT JOINING ------------------------ <#
infections_df = infections_df %>%
  left_join(
    th_grs_lookup %>% rename(th_grs = grs),
    by = 'eid'
  ) %>%
  left_join(
    fg_grs_lookup %>% rename(fg_grs = grs),
    by = 'eid'
  ) %>%
  left_join(
    glyhba1c_grs_lookup %>% rename(hba1c_glyc_grs = grs),
    by = 'eid'
  ) %>%
  left_join(
    nonhba1c_grs_lookup %>% rename(hba1c_nonglyc_grs = grs),
    by = 'eid'
  )
```


``` {r MANUAL WORK}
#> ----------- Checking if duplicated() values occur multiple times --------- <#

unique(viral_eids[duplicated(viral_eids)])[1:5]
# 1020467 1091083 1166305 1204829 1225784

which(viral_eids == 1020467)
# [1]    2    3  737 3031

which(viral_eids == 1091083)
# [1]   11   12 2288

which(viral_eids == 1166305)
# [1]  22  23 755
```

``` {r Viewing Cohort summary}
summary(infections_df)
```

``` {r Saving Cohort}
#> Export 212 MiB dataframe of infections to Harry's New Project
#> At £0.0141/GB Per month = 0.223 * 0.0141 / 30 = £0.0001 per day
filename = paste0("infections_df_",Sys.Date(),".csv")

write_csv(
  infections_df,
  file = filename
)

system(paste0('dx upload ', filename))
```
